import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/sidebar/sidebar";
import Navbar from "./ui/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
            <Sidebar />
          <div className="main-content">
            <Navbar/>
            <div className="">{children}</div>
          </div>
          
        </main>

      </body>
    </html>
  );
}
